'use client';
import { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import { motion, AnimatePresence, useReducedMotion } from 'framer-motion';
import { ArrowUpRight, ArrowRight, Check, Plus, Minus, MessageCircle, UserRound } from 'lucide-react';
import { Swiper, SwiperSlide } from 'swiper/react';
import { A11y, Keyboard } from 'swiper/modules';
import 'swiper/css';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { Button, Label } from './AcademyUI';
import { Contact } from './Experience';
import AcademyMotion from './AcademyMotion';

const strengths=[['Practical learning','Learn through activity-based training and hands-on sessions. Put understanding into practice.'],['Industry-relevant skills','Develop skills that matter beyond textbooks, with communication and service at the core.'],['Professional development','Build confidence, discipline and presentation skills for professional environments.'],['Career-focused approach','Learn with a direction. Prepare for your next step through practical skill development.']];
const journey=[['Discover','Understand your interests and career direction.'],['Learn','Build foundation and industry-focused skills.'],['Practice','Apply your learning through practical activities.'],['Grow','Develop confidence and professional skills.'],['Prepare','Get ready for the next step in your career.']];
const questions=[['Who can apply to NXT Academy?','SSLC and PUC students interested in practical, career-focused Hospitality or Aviation training can enquire. Contact admissions to confirm the requirements for your chosen program.'],['What courses are offered?','NXT Academy offers career-focused training in Hospitality and Aviation, with an emphasis on practical learning, communication and professional development.'],['Is the course suitable after SSLC?','SSLC students can explore programs at NXT. Our admissions team can explain eligibility and help you understand which program matches your interests.'],['Is the course suitable after PUC?','PUC students can enquire about Hospitality and Aviation training. Speak with admissions about the curriculum, fees and available intakes.'],['Does the training include practical sessions?','Yes. The learning approach includes activity-based training, practical sessions and professional development. Ask admissions for the detailed curriculum of your selected course.'],['Where is NXT Academy located?','NXT Academy of Creative Studies is in Mangaluru, Karnataka. Call the admissions team for the exact campus address and directions.'],['How can I enquire about admissions?','Call or WhatsApp +91 821 733 7597, email nxtacademy69@gmail.com, or use the form below to prepare your enquiry for WhatsApp.']];
function Why(){return <section id="why-nxt" className="section why-section"><div className="why-heading"><Label>THE NXT DIFFERENCE</Label><h2>Why NXT?<br/><em>Because growth<br/>takes practice.</em></h2><p>A learning experience built around the skills you need and the person you’re becoming.</p><div className="why-photo"><Image src="/academy-learning.webp" fill unoptimized sizes="40vw" alt="Illustrative classroom collaboration with a mentor"/></div></div><div className="strengths">{strengths.map(([title,text],i)=><div className="strength" key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></section>}
function Learning(){const activities=['Presentation practice','Communication sessions','Role play & group activities','Professional grooming','Practical demonstrations','Mock service scenarios','Career guidance'];return <section className="section learning-section"><div><Label>THE LEARNING EXPERIENCE</Label><h2>Less watching.<br/><em>More doing.</em></h2><p>Learn by doing. Build understanding through active participation, shared ideas and everyday practice.</p><Button href="#student-life" secondary>Explore student life</Button></div><div className="activity-grid">{activities.map((a,i)=><div key={a}><span>0{i+1}</span><h3>{a}</h3><ArrowUpRight size={20}/></div>)}</div></section>}
function Journey(){return <section className="section journey-section"><Label>YOUR PROGRESS, STEP BY STEP</Label><h2>From student <em>to career-ready.</em></h2><div className="journey-track"><div className="journey-line"/>{journey.map(([title,text],i)=><div className="journey-step" key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></div>)}</div></section>}
function Manifesto(){const ref=useRef<HTMLElement>(null);const reduced=useReducedMotion();useEffect(()=>{if(reduced)return;gsap.registerPlugin(ScrollTrigger);const ctx=gsap.context(()=>{gsap.utils.toArray<HTMLElement>('.learning-word').forEach(w=>gsap.fromTo(w,{opacity:.28,y:15},{opacity:1,y:0,scrollTrigger:{trigger:w,start:'top 90%',end:'top 65%',scrub:true}}));gsap.to(ref.current,{backgroundColor:'#dff6e8',scrollTrigger:{trigger:ref.current,start:'top 75%',end:'bottom 60%',scrub:true}})},ref);return()=>ctx.revert()},[reduced]);return <section ref={ref} className="learning-manifesto"><Label>SKILLS THAT MOVE YOU FORWARD</Label><div>{['Learn.','Practice.','Communicate.','Grow.'].map(w=><span key={w} className="learning-word">{w}</span>)}</div><p>Become career-ready. One skill at a time.</p></section>}
function Life(){const gallery=[{title:'Learning together',src:'/academy-learning.webp',local:true},{title:'Communication & collaboration',src:'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=85',local:false},{title:'Student interaction',src:'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=85',local:false}];return <section id="student-life" className="section life-section"><div className="section-heading"><div><Label>BEYOND THE TEXTBOOK</Label><h2>Life at <em>NXT.</em></h2></div><p>New skills. Shared experiences.<br/>A little more confidence, every day.</p></div><Swiper modules={[A11y,Keyboard]} keyboard={{enabled:true,onlyInViewport:true}} slidesPerView={1.12} spaceBetween={20} breakpoints={{760:{slidesPerView:2.25},1200:{slidesPerView:2.7}}}>{gallery.map((g,i)=><SwiperSlide key={g.title}><figure><Image src={g.src} fill unoptimized={g.local} sizes="(max-width:760px) 90vw, 40vw" alt={g.title+' — illustrative learning imagery'}/><figcaption><span>0{i+1} / THE ACADEMY EXPERIENCE</span><h3>{g.title}</h3><ArrowUpRight size={21}/></figcaption></figure></SwiperSlide>)}</Swiper><div className="gallery-note"><span>Illustrative imagery. Replace with approved NXT classroom and campus photographs.</span><span>Drag to explore <ArrowRight size={16}/></span></div></section>}
function Eligibility(){return <section id="admissions" className="section eligibility-section"><div><Label>WHO CAN APPLY?</Label><h2>Finished SSLC or PUC?<br/><em>Your next chapter is here.</em></h2><p>Students looking for practical, career-focused training in Hospitality and Aviation can explore programs at NXT Academy.</p><Button>Talk to our admissions team</Button></div><div className="qualification"><span>YOUR STARTING POINT</span><strong>SSLC <em>&</em> PUC</strong><p>Your interests. Your skills.<br/>A direction that’s yours.</p><small>Program-specific eligibility confirmed by admissions.</small></div></section>}
function Parents(){return <section className="section parent-section"><div><Label>FOR PARENTS & GUARDIANS</Label><h2>A stronger start<br/><em>for their future.</em></h2><p>Choosing the next step after school is an important family decision. Get a clear understanding of what your child will learn and how the program supports their development.</p><a className="text-link" href="tel:+918217337597">Speak with our admissions team<ArrowUpRight size={18}/></a></div><div className="parent-list">{[['Learning with structure','Understand the program, learning activities and expectations before you enrol.'],['Skills with practical value','Explore training focused on communication, service and professional readiness.'],['Confidence through development','A focus on presentation, discipline and the confidence to participate.']].map(([title,text])=><div key={title}><Check size={20}/><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></section>}
function Stories(){return <section className="section stories-section"><div className="section-heading"><div><Label>OUR STUDENTS, IN THEIR OWN WORDS</Label><h2>Student <em>experiences.</em></h2></div><p>Real stories will be shared here<br/>with each student’s permission.</p></div><div className="testimonial-grid">{['Hospitality','Aviation'].map(course=><article key={course}><span className="placeholder-label">TESTIMONIAL PLACEHOLDER</span><p>“Replace with real student testimonial.”</p><div><span className="student-avatar"><UserRound size={23}/></span><span>Student name<small>{course} · Photo and approved story to be added</small></span></div></article>)}</div></section>}
function Faq(){const [open,setOpen]=useState<number|null>(0);return <section className="section faq-section"><div><Label>HERE TO HELP</Label><h2>A little clarity<br/><em>for your next step.</em></h2><p>Questions from students and parents,<br/>answered simply.</p></div><div>{questions.map(([q,a],i)=><div className="faq-item" key={q}><h3><button onClick={()=>setOpen(open===i?null:i)} aria-expanded={open===i} aria-controls={'answer-'+i} id={'question-'+i}>{q}{open===i?<Minus size={18}/>:<Plus size={18}/>}</button></h3><AnimatePresence initial={false}>{open===i&&<motion.div id={'answer-'+i} role="region" aria-labelledby={'question-'+i} initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} transition={{duration:.25}} style={{overflow:'hidden'}}><p>{a}</p></motion.div>}</AnimatePresence></div>)}</div></section>}
function Admissions(){return <section className="section final-cta"><div><Label>LET’S TAKE THE FIRST STEP</Label><h2>Your next chapter<br/><em>starts here.</em></h2><p>Take the first step toward skill-based career training<br/>at NXT Academy of Creative Studies.</p></div><div><Button>Enquire now</Button><a href="https://wa.me/918217337597" className="whatsapp-link" target="_blank" rel="noopener noreferrer"><MessageCircle size={19}/>WhatsApp us<ArrowUpRight size={17}/></a></div><div className="cta-lines" aria-hidden="true"/></section>}
export default function AcademySections(){return <><Why/><Learning/><Journey/><Manifesto/><Life/><Eligibility/><Parents/><Stories/><Faq/><Admissions/><Contact/><AcademyMotion/></>}
